"""phase 3 domain schema

Revision ID: f2f5fb78a777
Revises: 0001_initial
Create Date: 2026-09-04 11:41:23.333009
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_domain_schema"
down_revision: str | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain",
        sa.Column("name", sa.String(length=253), nullable=False),
        sa.Column("name_normalized", sa.String(length=253), nullable=False),
        sa.Column("tld", sa.String(length=63), nullable=True),
        sa.Column("is_public_suffix", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain")),
        sa.UniqueConstraint("name_normalized", name="uq_domain_name_normalized"),
    )
    with op.batch_alter_table("domain", schema=None) as batch_op:
        batch_op.create_index("ix_domain_name_normalized", ["name_normalized"], unique=False)

    op.create_table(
        "evidence",
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=True),
        sa.Column("value_json", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("reference", sa.String(length=1024), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("extraction_method", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 and confidence <= 100", name=op.f("ck_evidence_confidence_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
        sa.UniqueConstraint(
            "entity_type",
            "entity_id",
            "field",
            "source",
            "content_hash",
            name="uq_evidence_observation",
        ),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index("ix_evidence_collected_at", ["collected_at"], unique=False)
        batch_op.create_index("ix_evidence_content_hash", ["content_hash"], unique=False)
        batch_op.create_index("ix_evidence_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("ix_evidence_observed_at", ["observed_at"], unique=False)
        batch_op.create_index("ix_evidence_source", ["source"], unique=False)

    op.create_table(
        "external_account",
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("identifier", sa.String(length=190), nullable=False),
        sa.Column("identifier_normalized", sa.String(length=190), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("profile_url", sa.String(length=1024), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("linked_website", sa.String(length=1024), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_account")),
        sa.UniqueConstraint(
            "platform", "identifier_normalized", name="uq_external_account_platform_identifier"
        ),
    )
    with op.batch_alter_table("external_account", schema=None) as batch_op:
        batch_op.create_index(
            "ix_external_account_identifier_normalized", ["identifier_normalized"], unique=False
        )

    op.create_table(
        "ioc",
        sa.Column("ioc_type", sa.String(length=24), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("value_normalized", sa.String(length=512), nullable=False),
        sa.Column("linked_entity_type", sa.String(length=32), nullable=True),
        sa.Column("linked_entity_id", sa.String(length=36), nullable=True),
        sa.Column("times_observed", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ioc")),
        sa.UniqueConstraint("ioc_type", "value_normalized", name="uq_ioc_type_value"),
    )
    with op.batch_alter_table("ioc", schema=None) as batch_op:
        batch_op.create_index("ix_ioc_type", ["ioc_type"], unique=False)
        batch_op.create_index("ix_ioc_value_normalized", ["value_normalized"], unique=False)

    op.create_table(
        "ip",
        sa.Column("address", sa.String(length=45), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("asn", sa.Integer(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ip")),
        sa.UniqueConstraint("address", name="uq_ip_address"),
    )
    with op.batch_alter_table("ip", schema=None) as batch_op:
        batch_op.create_index("ix_ip_address", ["address"], unique=False)

    op.create_table(
        "message",
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=False),
        sa.Column("author_account_id", sa.String(length=36), nullable=True),
        sa.Column("author_username", sa.String(length=64), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reply_to_message_id", sa.BigInteger(), nullable=True),
        sa.Column("forwarded_from", sa.String(length=255), nullable=True),
        sa.Column("views", sa.BigInteger(), nullable=True),
        sa.Column("urls_json", sa.Text(), nullable=True),
        sa.Column("usernames_json", sa.Text(), nullable=True),
        sa.Column("entities_json", sa.Text(), nullable=True),
        sa.Column("media_meta_json", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=512), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message")),
        sa.UniqueConstraint(
            "source_type", "source_id", "message_id", name="uq_message_source_msgid"
        ),
    )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.create_index("ix_message_author_account_id", ["author_account_id"], unique=False)
        batch_op.create_index("ix_message_message_id", ["message_id"], unique=False)
        batch_op.create_index("ix_message_posted_at", ["posted_at"], unique=False)
        batch_op.create_index("ix_message_source", ["source_type", "source_id"], unique=False)

    op.create_table(
        "relationship",
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("rel_type", sa.String(length=48), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 and confidence <= 100", name=op.f("ck_relationship_confidence_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship")),
        sa.UniqueConstraint(
            "source_type",
            "source_id",
            "target_type",
            "target_id",
            "rel_type",
            name="uq_relationship_edge",
        ),
    )
    with op.batch_alter_table("relationship", schema=None) as batch_op:
        batch_op.create_index("ix_relationship_last_seen", ["last_seen"], unique=False)
        batch_op.create_index("ix_relationship_rel_type", ["rel_type"], unique=False)
        batch_op.create_index("ix_relationship_source", ["source_type", "source_id"], unique=False)
        batch_op.create_index("ix_relationship_target", ["target_type", "target_id"], unique=False)

    op.create_table(
        "telegram_account",
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("username_normalized", sa.String(length=64), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_scam", sa.Boolean(), nullable=False),
        sa.Column("photo_reference", sa.String(length=255), nullable=True),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_account")),
        sa.UniqueConstraint("telegram_id", name="uq_telegram_account_telegram_id"),
    )
    with op.batch_alter_table("telegram_account", schema=None) as batch_op:
        batch_op.create_index("ix_telegram_account_telegram_id", ["telegram_id"], unique=False)
        batch_op.create_index(
            "ix_telegram_account_username_normalized", ["username_normalized"], unique=False
        )

    op.create_table(
        "telegram_channel",
        sa.Column("posting_frequency_per_day", sa.Float(), nullable=True),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("username_normalized", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("participants_count", sa.BigInteger(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_channel")),
        sa.UniqueConstraint("telegram_id", name="uq_telegram_channel_telegram_id"),
    )
    with op.batch_alter_table("telegram_channel", schema=None) as batch_op:
        batch_op.create_index("ix_telegram_channel_telegram_id", ["telegram_id"], unique=False)
        batch_op.create_index(
            "ix_telegram_channel_username_normalized", ["username_normalized"], unique=False
        )

    op.create_table(
        "telegram_group",
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("username_normalized", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("participants_count", sa.BigInteger(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telegram_group")),
        sa.UniqueConstraint("telegram_id", name="uq_telegram_group_telegram_id"),
    )
    with op.batch_alter_table("telegram_group", schema=None) as batch_op:
        batch_op.create_index("ix_telegram_group_telegram_id", ["telegram_id"], unique=False)
        batch_op.create_index(
            "ix_telegram_group_username_normalized", ["username_normalized"], unique=False
        )

    op.create_table(
        "url",
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("url_normalized", sa.String(length=2048), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("scheme", sa.String(length=16), nullable=True),
        sa.Column("host", sa.String(length=253), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_url")),
        sa.UniqueConstraint("url_hash", name="uq_url_hash"),
    )
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.create_index("ix_url_hash", ["url_hash"], unique=False)
        batch_op.create_index("ix_url_host", ["host"], unique=False)

    op.create_table(
        "user",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name="uq_user_email"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index("ix_user_role", ["role"], unique=False)
        batch_op.create_index("ix_user_telegram_user_id", ["telegram_user_id"], unique=False)

    op.create_table(
        "username",
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=190), nullable=False),
        sa.Column("value_normalized", sa.String(length=190), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_username")),
        sa.UniqueConstraint("platform", "value_normalized", name="uq_username_platform_value"),
    )
    with op.batch_alter_table("username", schema=None) as batch_op:
        batch_op.create_index("ix_username_value_normalized", ["value_normalized"], unique=False)

    op.create_table(
        "target",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("value_normalized", sa.String(length=512), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_target_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target")),
        sa.UniqueConstraint(
            "user_id", "kind", "value_normalized", name="uq_target_user_kind_value"
        ),
    )
    with op.batch_alter_table("target", schema=None) as batch_op:
        batch_op.create_index("ix_target_user_id", ["user_id"], unique=False)
        batch_op.create_index("ix_target_value_normalized", ["value_normalized"], unique=False)

    op.create_table(
        "report",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("content_json", sa.Text(), nullable=True),
        sa.Column("artifacts_json", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_report_job_id_job"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target.id"],
            name=op.f("fk_report_target_id_target"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_report_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report")),
    )
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.create_index("ix_report_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_report_status", ["status"], unique=False)
        batch_op.create_index("ix_report_target_id", ["target_id"], unique=False)
        batch_op.create_index("ix_report_user_id", ["user_id"], unique=False)

    op.create_table(
        "search",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("query", sa.String(length=1024), nullable=False),
        sa.Column("filters_json", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_search_job_id_job"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target.id"],
            name=op.f("fk_search_target_id_target"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_search_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search")),
    )
    with op.batch_alter_table("search", schema=None) as batch_op:
        batch_op.create_index("ix_search_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_search_target_id", ["target_id"], unique=False)
        batch_op.create_index("ix_search_user_id", ["user_id"], unique=False)

    op.create_table(
        "watchlist",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("value_normalized", sa.String(length=512), nullable=False),
        sa.Column("sources_json", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_marker", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target.id"],
            name=op.f("fk_watchlist_target_id_target"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_watchlist_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist")),
        sa.UniqueConstraint(
            "user_id", "kind", "value_normalized", name="uq_watchlist_user_kind_value"
        ),
    )
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.create_index("ix_watchlist_active", ["is_active"], unique=False)
        batch_op.create_index("ix_watchlist_user_id", ["user_id"], unique=False)

    op.create_table(
        "search_result",
        sa.Column("search_id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("matched_terms_json", sa.Text(), nullable=True),
        sa.Column("evidence_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["search.id"],
            name=op.f("fk_search_result_search_id_search"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_result")),
    )
    with op.batch_alter_table("search_result", schema=None) as batch_op:
        batch_op.create_index("ix_search_result_entity", ["entity_type", "entity_id"], unique=False)
        batch_op.create_index("ix_search_result_search_id", ["search_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_result", schema=None) as batch_op:
        batch_op.drop_index("ix_search_result_search_id")
        batch_op.drop_index("ix_search_result_entity")

    op.drop_table("search_result")
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.drop_index("ix_watchlist_user_id")
        batch_op.drop_index("ix_watchlist_active")

    op.drop_table("watchlist")
    with op.batch_alter_table("search", schema=None) as batch_op:
        batch_op.drop_index("ix_search_user_id")
        batch_op.drop_index("ix_search_target_id")
        batch_op.drop_index("ix_search_created_at")

    op.drop_table("search")
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.drop_index("ix_report_user_id")
        batch_op.drop_index("ix_report_target_id")
        batch_op.drop_index("ix_report_status")
        batch_op.drop_index("ix_report_created_at")

    op.drop_table("report")
    with op.batch_alter_table("target", schema=None) as batch_op:
        batch_op.drop_index("ix_target_value_normalized")
        batch_op.drop_index("ix_target_user_id")

    op.drop_table("target")
    with op.batch_alter_table("username", schema=None) as batch_op:
        batch_op.drop_index("ix_username_value_normalized")

    op.drop_table("username")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index("ix_user_telegram_user_id")
        batch_op.drop_index("ix_user_role")

    op.drop_table("user")
    with op.batch_alter_table("url", schema=None) as batch_op:
        batch_op.drop_index("ix_url_host")
        batch_op.drop_index("ix_url_hash")

    op.drop_table("url")
    with op.batch_alter_table("telegram_group", schema=None) as batch_op:
        batch_op.drop_index("ix_telegram_group_username_normalized")
        batch_op.drop_index("ix_telegram_group_telegram_id")

    op.drop_table("telegram_group")
    with op.batch_alter_table("telegram_channel", schema=None) as batch_op:
        batch_op.drop_index("ix_telegram_channel_username_normalized")
        batch_op.drop_index("ix_telegram_channel_telegram_id")

    op.drop_table("telegram_channel")
    with op.batch_alter_table("telegram_account", schema=None) as batch_op:
        batch_op.drop_index("ix_telegram_account_username_normalized")
        batch_op.drop_index("ix_telegram_account_telegram_id")

    op.drop_table("telegram_account")
    with op.batch_alter_table("relationship", schema=None) as batch_op:
        batch_op.drop_index("ix_relationship_target")
        batch_op.drop_index("ix_relationship_source")
        batch_op.drop_index("ix_relationship_rel_type")
        batch_op.drop_index("ix_relationship_last_seen")

    op.drop_table("relationship")
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_index("ix_message_source")
        batch_op.drop_index("ix_message_posted_at")
        batch_op.drop_index("ix_message_message_id")
        batch_op.drop_index("ix_message_author_account_id")

    op.drop_table("message")
    with op.batch_alter_table("ip", schema=None) as batch_op:
        batch_op.drop_index("ix_ip_address")

    op.drop_table("ip")
    with op.batch_alter_table("ioc", schema=None) as batch_op:
        batch_op.drop_index("ix_ioc_value_normalized")
        batch_op.drop_index("ix_ioc_type")

    op.drop_table("ioc")
    with op.batch_alter_table("external_account", schema=None) as batch_op:
        batch_op.drop_index("ix_external_account_identifier_normalized")

    op.drop_table("external_account")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index("ix_evidence_source")
        batch_op.drop_index("ix_evidence_observed_at")
        batch_op.drop_index("ix_evidence_entity")
        batch_op.drop_index("ix_evidence_content_hash")
        batch_op.drop_index("ix_evidence_collected_at")

    op.drop_table("evidence")
    with op.batch_alter_table("domain", schema=None) as batch_op:
        batch_op.drop_index("ix_domain_name_normalized")

    op.drop_table("domain")
    # ### end Alembic commands ###
